# Allow connections from other containers
listen_addresses = '*'

#Enable streaming replication
wal_level = replication
# Numver of wal sender processes
max_wal_senders = 10

#Number of replication slots
max_replication_slots = 10

# Keep enough wal files for replicas
wal_keep_size = 256MB