name: Backend Deploy
on:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"
      - "packages/**"
      - "pnpm-lock.yaml"
      - "package.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm turbo lint
      - run: pnpm turbo build
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker Image
        run: | 
          docker push \
          ${{ secrets.ECR_REPOSITORY }}:latest
      - name: Deploy EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/shop-now
            docker compose pull
            docker compose up -d
            docker image prune -f