name: HAProxy CD

on:
  push:
    branches:
      - main

    paths:
      - "docker/haproxy/**"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build HAProxy
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/shop-now-haproxy:${{ github.sha }} \
            -t ${{ steps.login-ecr.outputs.registry }}/shop-now-haproxy:latest \
            -f docker/haproxy/Dockerfile \
            docker/haproxy

      - name: Push HAProxy
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/shop-now-haproxy:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/shop-now-haproxy:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd ~/shop-now

            echo "Writing image tags..."

            cat > .env <<EOF
            ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
            HAPROXY_IMAGE_TAG=${{ github.sha }}
            EOF

            echo "Verifying .env contents:"
            cat .env

            echo "Logging in to ECR on EC2..."
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            echo "Pulling latest HAProxy image..."
            docker compose pull haproxy

            echo "Starting HAProxy..."
            docker compose up -d haproxy

            echo "Cleaning old images..."
            docker image prune -f

            echo "HAProxy deployment completed successfully!"