name: HAProxy CD

on:
  push:
    branches:
      - main

    paths:
      - "docker/haproxy/**"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build HAProxy
        run: |
          docker build \
            -t $ECR_REGISTRY/shop-now-haproxy:${{ github.sha }} \
            -t $ECR_REGISTRY/shop-now-haproxy:latest \
            -f docker/haproxy/Dockerfile \
            docker/haproxy

      - name: Push HAProxy
        run: |
          docker push $ECR_REGISTRY/shop-now-haproxy:${{ github.sha }}
          docker push $ECR_REGISTRY/shop-now-haproxy:latest

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/shop-now

            docker compose pull haproxy

            docker compose up -d haproxy

            docker image prune -f